service: shopify-server
app: shopify
tenant: 8eecf0d2

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: ${env:AWS_REGION}
  profile: ${env:AWS_PROFILE}
  runtime: ${env:AWS_RUNTIME}

functions:
  shopify-app:
    handler: src/server/ts/functions/shopify/app.handler
    events:
      - http:
          method: get
          path: shopify/{path+}
      - http:
          method: get
          path: shopify
  shopify-setup:
    handler: src/server/ts/functions/shopify/setup.handler
    events:
      - http:
          method: get
          path: api/shopify/setup
          integration: lambda-proxy
  shopify-callback:
    handler: src/server/ts/functions/shopify/callback.handler
    events:
      - http:
          method: get
          path: api/shopify/callback
          integration: lambda-proxy
  shopify-proxy:
    handler: src/server/ts/functions/shopify/proxy.handler
    events:
      - http:
          method: post
          path: api/shopify/proxy
          integration: lambda-proxy

custom:
  serverless-offline:
    # host: ${env:API_ADDRESS}
    port: ${env:API_HTTP_PORT}
    # port: ${env:API_HTTPS_PORT}
    # httpsProtocol: ".certificates"
  dotenv:
    path: .env
  webpack:
    webpackConfig: 'src/server/webpack.config.js'
    packager: 'yarn'
