service: shopify-server
app: shopify-order-printer
tenant: 8eecf0d2

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  region: ap-southeast-2
  profile: ${env:AWS_PROFILE}
  runtime: ${env:AWS_RUNTIME}

functions:
  shopify-app:
    handler: src/server/ts/functions/shopify/app.handler
    events:
      - http:
          method: get
          path: shopify/{path+}
      - http:
          method: get
          path: shopify
  shopify-setup:
    handler: src/server/ts/functions/shopify/setup.handler
    events:
      - http:
          method: get
          path: api/shopify/setup
          integration: lambda-proxy
  shopify-callback:
    handler: src/server/ts/functions/shopify/callback.handler
    events:
      - http:
          method: get
          path: api/shopify/callback
          integration: lambda-proxy
  shopify-proxy:
    handler: src/server/ts/functions/shopify/proxy.handler
    events:
      - http:
          method: post
          path: api/shopify/proxy
          integration: lambda-proxy

custom:
  serverless-offline:
    # host: ${env:API_ADDRESS}
    port: ${env:API_HTTP_PORT}
    # port: ${env:API_HTTPS_PORT}
    # httpsProtocol: ".certificates"
  dotenv:
    path: .env
  webpack:
    webpackConfig: 'src/server/webpack.config.js'
    packager: 'yarn'
  customDomain:
    domainName: shopify.aws.8eecf0d2.com
    certificateName: 8eecf0d2
    stage: ${self:provider.stage}
    basePath: ""
    endpointType: "regional"
